# Test with SSL - Standalone
version: "2"
services:
    proxy:
        build: ../common/nginx
        container_name: skel_proxy
        volumes:
            - ../common/ssl:/etc/ssl/private
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../common/nginx/rotate-log.sh:/etc/nginx/rotate-log.sh
            - ./nginx/sites-available/default:/etc/nginx/conf.d/default.conf
            - ../common/nginx/includes:/etc/nginx/includes
            - ../../frontend:/usr/share/nginx/html
            - /var/log/nginx:/var/log/nginx
        depends_on: 
            - api
        ports:
            - 80:80
            - 443:443
        network_mode: host

    api:
        build: ../common/pm2
        container_name: skel
        volumes:
            - /var/log/skel:/root/.pm2/logs
            - ../../api:/app
        depends_on: 
            - db
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=test
        command: "pm2-docker start --auto-exit --env test process.yml"
        network_mode: host
    
    cron:
        build: ../common/cron
        container_name: skel_cron
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # sibling containers instead of child containers
            - /var/log/skel:/var/log/skel
            - ../common/cron/root:/etc/crontabs/root
            - ../../api/cron:/home/node
        network_mode: host
    
    db:
        image: mongo:3.4.10
        container_name: skel_db
        volumes:
            - "./mongo_data:/data/db"
        network_mode: host

    cache:
        image: redis:3.0.7-alpine
        container_name: skel_cache
        volumes: 
            - ../common/redis:/usr/local/etc/redis
        command: "redis-server /usr/local/etc/redis/redis.conf"
        network_mode: host

networks:
    default:
        external:
            name: "host"