# Production without SSL
version: "2"
services:
    proxy:
        build: ../common/nginx
        container_name: skel_proxy
        volumes:
            - ../common/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available/default:/etc/nginx/conf.d/default.conf
            - ../common/nginx/includes:/etc/nginx/includes
            - ../common/nginx/rotate-log.sh:/etc/nginx/rotate-log.sh
            - ../../frontend:/usr/share/nginx/html
            - /var/log/nginx:/var/log/nginx
        depends_on: 
            - api
        ports:
            - 80:80
        network_mode: host

     api:
        build: ../common/pm2
        container_name: skel
        volumes:
            - /var/log/skel:/root/.pm2/logs
            - ../../api:/app
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=production
        network_mode: host

    cron:
        build: ../common/cron
        container_name: skel_cron
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # sibling containers instead of child containers
            - /var/log/skel:/var/log/skel
            - ../common/cron/root:/etc/crontabs/root
            - ../../api/cron:/home/node
        network_mode: host

networks:
    default:
        external:
            name: "host"